version: "3.9"
services:
    service1:
        container_name: service1
        build: .
        image: node-run
        command: npm run service1
        ports:
            - "3000:3000"
    service2:
        container_name: service2
        image: node-run
        command: npm run service2
        ports:
            - "3001:3001"
    service3:
        container_name: service3
        image: node-run
        command: node service3.js
        ports:
            - "3002:3002"
    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        ports:
            - "9090:9090"
    grafana:
        container_name: grafana
        image: grafana/grafana-enterprise:8.2.0
        ports:
            - "9999:3000"